spring:
    profile:
        active:
        - dev
---

spring:
    profile: dev    # 开发环境
    application:
        name: microservicecloud-config-youzhiyu-dev
        
---

spring:
    profile: test   # 测试环境
    application: 
        name: microservicecloud-config-youzhiyu-test
        
# 请保存为UTF-8格式
